#!/bin/sh

CONTAINERNAME=$1
CONTAINEREXPOSEDPORT=$2

if [ -z "$CONTAINERNAME" ]
then
    echo "Please add as first argument the targeted container name"
    exit 1
fi

if [ -z "$CONTAINEREXPOSEDPORT" ]
then
    echo "Please add as second argument the desired exposed port"
    exit 1
fi

PID=$(sudo docker ps | awk -v var="$CONTAINERNAME" '$2 == var {print $1}')

if [ -z "$PID" ]
then
    echo "Couldn't find a docker container named $CONTAINERNAME"
    exit 1
fi

STOP=$(sudo docker stop "$PID")
RM=$(sudo docker rm "$PID")

echo "Rebuilding container "$CONTAINERNAME""
echo $(sudo docker build -t "$CONTAINERNAME" .)

echo "Container "$CONTAINERNAME" is stopped and removed"
echo "Restarting "$CONTAINERNAME" on port "$CONTAINEREXPOSEDPORT""
echo $(sudo docker run -dp $2:$2 "$CONTAINERNAME")
